#!/bin/bash

if [ $# -ne 1 ]
then
  echo "Usage: new_project <project name>"
else
  mkdir "$1/"
  mkdir "$1/src"
  mkdir "$1/bin"
  mkdir "$1/obj"

  cp "template/Makefile" "$1/"
  cp "template/main.cpp" "$1/src/"

  perl -pi -w -e "s/TARGET/$1/g;" "$1/Makefile"
  perl -pi -w -e "s/TARGET/$1/g;" "$1/src/main.cpp"
fi
